### ISSUE TITLE
UpdateEditor

### ISSUE THREAD

**Issue by bengouts** [deepanshu88/ShinyEditor#1]
Hi !
First, thanks for this usefull package.
UpdateEditor does not seem to update the editor, even the minimum exemple.
Would you have a suggestion ?.
Ben

```
library(shiny)
library(ShinyEditor)

# UI
ui <- fluidPage(
  
  # Setup
  use_editor("API-Key"),
  titlePanel("HTML Generator"),
  editor(id='textcontent'),
  actionButton("updatedata", "Update Editor", icon = icon("edit"))
)


# Server
server <- function(input, output, session) {
  
  
  observeEvent(input$updatedata, {
    print("ok")
    UpdateEditor(session,
                 id = "textcontent",
                 text = "ca marche !")
    
  })
  
}

# Run App
shinyApp(ui = ui, server = server)

```

Here is my `sessionInfo()` 
```
R version 4.0.5 (2021-03-31)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 20.04.2 LTS

Matrix products: default
BLAS:   /usr/lib/x86_64-linux-gnu/blas/libblas.so.3.9.0
LAPACK: /usr/lib/x86_64-linux-gnu/lapack/liblapack.so.3.9.0

locale:
 [1] LC_CTYPE=fr_FR.UTF-8       LC_NUMERIC=C               LC_TIME=fr_FR.UTF-8        LC_COLLATE=fr_FR.UTF-8     LC_MONETARY=fr_FR.UTF-8    LC_MESSAGES=fr_FR.UTF-8   
 [7] LC_PAPER=fr_FR.UTF-8       LC_NAME=C                  LC_ADDRESS=C               LC_TELEPHONE=C             LC_MEASUREMENT=fr_FR.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] ShinyEditor_0.1.0 shiny_1.6.0      

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.6        digest_0.6.27     later_1.1.0.1     mime_0.10         R6_2.5.0          jsonlite_1.7.2    lifecycle_1.0.0   xtable_1.8-4      magrittr_2.0.1   
[10] cachem_1.0.4      rlang_0.4.10      promises_1.2.0.1  jquerylib_0.1.3   bslib_0.2.4       ellipsis_0.3.1    tools_4.0.5       httpuv_1.5.5      fastmap_1.1.0    
[19] compiler_4.0.5    htmltools_0.5.1.1 sass_0.3.1 
```

**Comment by deepanshu88** [comment]
What error you are getting? Can you check once on windows if you have? I'll look into it

**Comment by bengouts** [comment]
Hey ! Thanks for quick answer !
I don't get any error, but the editor don't update when I use `UpdateEditor`.
I tried on windows, and this problem did not happen.
Ben

**Comment by deepanshu88** [comment]
Thanks for confirmation. I will see if I can check on Linux. This demo app https://deeps.shinyapps.io/HTMLEditor/ is deployed on shinyapps.io which uses Ubuntu Linux as the base operating system

**Comment by bengouts** [comment]
That's weird... I have no clue on what is happening !

**Comment by ElenaDatak** [comment]
Hello, 

Thank you for this very usefull editor ! I have the same problem, the function `UpdateEditor()` works well on Windows, but doesn't on Linux... I've found a way to manage it : you have to include the js file shinyEditor.js of the package in the app. Considering my Shiny app is developped with `{golem}`, I copied the js file shinyEditor.js into the external ressources folder inst/app/www/ and it now works well.

**Comment by deepanshu88** [comment]
@ElenaDatak  Thanks for reporting issue. Can you check now on Linux after reinstalling the package?

**Comment by ElenaDatak** [comment]
@deepanshu88 sorry for the late answear, I've reinstalled the package and it still doesn't work.

**Comment by deepanshu88** [comment]
It should be working now. Thanks!
