### ISSUE TITLE
How to trigger editorText output?

### ISSUE THREAD

**Issue by swalkerCDD** [deepanshu88/ShinyEditor#3]
Hi -
First, thanks for a useful package! I have just started using it, but I am running into an issue. See below for a slightly modified version of your minimal example. Note that you have to press the button twice to actually get the output text to print. On the first press, the value is NULL. How can I access the output text/html immediately after editorText()? For example, if I wanted to write the text to a file.
```
library(shiny)
library(ShinyEditor)

# UI
ui <- fluidPage(
  
  # Setup
  use_editor(Sys.getenv("TINY_EDITOR_API_KEY")),
  titlePanel("HTML Generator"),
  
  # Text Input 1
  fluidRow(
    column(
      width = 6,
      editor('textcontent'),
      br(),
      actionButton(
        "print",
        "Print HTML to Console"
      ))
  )
  
)

# Server
server <- function(input, output, session) {
  
  # Generate HTML
  observeEvent(input$print, {
    
    editorText(session, editorid = 'textcontent', outputid = 'mytext')
    print(input$mytext)
    
  })
  
}

# Run App
shinyApp(ui = ui, server = server)
```

**Comment by deepanshu88** [comment]
The code below should work. Make sure to remove `print( )` within the `observeEvent( )` code.

```
observe({
    req(input$print)
    print(input$mytext)
  })

```

**Comment by swalkerCDD** [comment]
Thanks for the quick response! I figured out a similar solution shortly after I posted the issue. I have found another issue in the meantime, which I will post separately.
